spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect

ems2cad:
  datasource:
    platform: openedge
#    url: jdbc:datadirect:openedge://deserto:21039;databaseName=ems2cad
    jdbc-url: jdbc:datadirect:openedge://deserto:21039;databaseName=ems2cad
    username: pub
    password: pub
#    driverClassName: com.ddtek.jdbc.openedge.OpenEdgeDriver
    driver-class-name: com.ddtek.jdbc.openedge.OpenEdgeDriver

ems2mov:
  datasource:
    platform: openedge
#    url: jdbc:datadirect:openedge://deserto:21039;databaseName=ems2mov
    jdbc-url: jdbc:datadirect:openedge://deserto:21030;databaseName=ems2mov
    username: pub
    password: pub
#    driverClassName: com.ddtek.jdbc.openedge.OpenEdgeDriver
    driver-class-name: com.ddtek.jdbc.openedge.OpenEdgeDriver