spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect

  datasource:
    platform: openedge
    url: jdbc:datadirect:openedge://deserto:21039;databaseName=ems2cad
    username: pub
    password: pub
    driverClassName: com.ddtek.jdbc.openedge.OpenEdgeDriver